# Generated by Django 4.1.3 on 2022-11-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerencia", "0002_secretaria_orcamento_valor_orcamento_secretaria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secretaria",
            name="cnpj",
            field=models.CharField(max_length=50, null=True, verbose_name="CNPJ"),
        ),
    ]
