# Generated by Django 4.1.3 on 2022-11-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerencia", "0004_alter_orcamento_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="dt_entregue",
            field=models.DateField(blank=True, null=True, verbose_name="Data entregue"),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="dt_nota",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data nota gerada"
            ),
        ),
    ]
